<?php

class PropertyController extends MobileController
{
    public function init()
{
    parent::init(); // TODO: Change the autogenerated stub

//    $encrypt_id = isset($_GET['encrypt_id']) ? $_GET['encrypt_id'] : '';
//    //判断用户是否登录
//    if (!empty($encrypt_id)) {
//        if (!isset(Yii::app()->session[$encrypt_id . 'user_id']) || empty(Yii::app()->session[$encrypt_id . 'user_id'])) {
//            $proprietor = Proprietor::model()->find('user_id = :user_id', array(':user_id' => Yii::app()->session[$encrypt_id . 'user_id']));
//
//            if (Yii::app()->controller->action != 'review') {
//                if ($proprietor->verify_status == PROPRIETOR_VERIFY_STATUS_PENDING_AUDIT) {
//                    $this->createUrl('Ucenter/Review');
//                }
//                if ($proprietor->verify_status == PROPRIETOR_VERIFY_STATUS_REJECT) {
//                    $this->createUrl('Ucenter/ReviewNopass');
//                }
//                if ($proprietor->verify_status == PROPRIETOR_VERIFY_STATUS_PASS) {
//                    $this->createUrl('Ucenter/Index');
//                }
//            }
//        }
//    }

}


    /** 判断用户是否登录
     * @param $encrypt_id
     */
    public function checkLogin($encrypt_id, $goUrl = '')
    {
        //判断session里是否存在用户id
        if (!isset(Yii::app()->session[$encrypt_id . 'user_id']) || empty(Yii::app()->session[$encrypt_id . 'user_id'])) {
            $this->redirect(Yii::app()->createUrl('mobile/property/user/login', array(
                'encrypt_id' => $encrypt_id
            )));
        }
    }

    /**
     * 获取商户加密id
     */
    public function getEncryptId() {
        $encrypt_id = '';
        if (isset($_GET['encrypt_id']) && $_GET['encrypt_id']) {
            $encrypt_id = $_GET['encrypt_id'];
        }

        return $encrypt_id;
    }

    /**
     *获取用户id
     */
    public function getUserId() {
        return Yii::app()->session[$this->getEncryptId() . 'user_id'];
    }


}

